Add ability to set keyboard shorcuts
l10nelw/select-tabs pull request #1
Opened 2022-06-04 02:26 UTC by liljaylj

... using browser.commands API.

Additionally, added new "Clear selection" command. It is useful if you prefer keyboard-driven navigation.

2022-10-01 10:35 UTC, l10nelw requested changes
This is great idea @liljaylj. Do you normally navigate tabs via keyboard? How do you do it?

2022-10-01 10:35 UTC, l10nelw commented on background/background.js
> +        for (const [name, title] of Object.entries(commands)) {
Again, reserving plural names for arrays. Most objects functioning as 'dictionaries' (like 'maps', except not using the Map type) in this repo are given a `Dict` suffix.

```suggestion
function hydrateCommandDescriptions(groupDict) {
    for (const [group, commandDict] of Object.entries(groupDict)) {
        for (const [name, title] of Object.entries(commandDict)) {
```

Also please move this function above `function buildMenu()` to be consistent with your other command-related code (command first then menu).

2022-10-01 10:35 UTC, l10nelw commented on background/get.js
> +  return [ targetTab ];
This is not the expectation if you invoke it via context menu. This command should return the active tab.

2022-10-01 10:35 UTC, l10nelw commented on menudata.js
> +        clearSelection:         'Clear selectio&n',
```suggestion
    'Other': {
        none:         'Clear selection (&Z)',
```
Note that the commands are named to reflect their outcomes. So I prefer to call it `none`.

I don't feel `N` is right for this command. `C` is already taken. `Z` seems appropriate, it reminds us of 'undo'. Your hydrate function will need to remove `(&?)` as well.

2023-02-12 03:22 UTC, ces42 commented
What is the holdup on this? I would love to see this merged.

2023-04-04 11:35 UTC, merged

2023-04-04 12:54 UTC, l10nelw commented
@ces42 @liljaylj merged.